# Generated by Django 3.1.4 on 2023-08-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0060_offers_button_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='message',
        ),
    ]
